# Generated by Django 5.2.15 on 2026-06-19 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagent',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='photo',
            field=models.ImageField(blank=True, upload_to='agents/'),
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_agent_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='vehicle_type',
            field=models.CharField(choices=[('bicycle', 'Bicycle'), ('bike', 'Motorbike'), ('scooter', 'Scooter'), ('van', 'Delivery Van')], default='bike', max_length=20),
        ),
    ]
