# Generated by Django 5.2.15 on 2026-06-19 17:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0002_deliveryagent_email_deliveryagent_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(default='info', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_notifications', to='store.deliveryagent')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_notifications', to='store.order')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ready', 'Ready for Delivery'), ('accepted', 'Accepted'), ('store_picked', 'Picked From Store'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='ready', max_length=30)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('picked_from_store_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_assignments', to='store.deliveryagent')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_assignment', to='store.order')),
            ],
            options={
                'ordering': ('delivery_time', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='store.deliveryagent')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_tracking_events', to='store.order')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='PickupAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('reached', 'Reached Customer'), ('collected', 'Clothes Collected'), ('store_delivered', 'Delivered to Store'), ('cancelled', 'Cancelled')], default='assigned', max_length=30)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('reached_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_to_store_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_assignments', to='store.deliveryagent')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_assignment', to='store.order')),
            ],
            options={
                'ordering': ('pickup_time',),
            },
        ),
        migrations.CreateModel(
            name='AgentEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('pickup', 'Customer Pickup'), ('delivery', 'Customer Delivery')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('earned_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='store.deliveryagent')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_earnings', to='store.order')),
            ],
            options={
                'ordering': ('-earned_on',),
                'constraints': [models.UniqueConstraint(fields=('agent', 'order', 'task_type'), name='unique_agent_order_task_earning')],
            },
        ),
    ]
